### PR TITLE
Remove ccache from github action

### PR DESCRIPTION
**Pull request by tylerjw**
This is probably a bug that should be fixed upstream.  This should hopefully fix the reason my last PR failed to build.

### CODE REVIEW

**Comment by tylerjw** [comment]
Sadness, this is still failing:

```
Starting >>> warehouse_ros
  --- stderr: warehouse_ros
  CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
    The C compiler
  
      "/usr/lib/ccache/cc"
  
    is not able to compile a simple test program.
  
    It fails with the following output:
  
      Change Dir: /root/target_ws/build/warehouse_ros/CMakeFiles/CMakeTmp
      
      Run Build Command(s):/usr/bin/make cmTC_af595/fast && /usr/bin/make -f CMakeFiles/cmTC_af595.dir/build.make CMakeFiles/cmTC_af595.dir/build
      make[1]: Entering directory '/root/target_ws/build/warehouse_ros/CMakeFiles/CMakeTmp'
      Building C object CMakeFiles/cmTC_af595.dir/testCCompiler.c.o
      /usr/lib/ccache/cc    -o CMakeFiles/cmTC_af595.dir/testCCompiler.c.o   -c /root/target_ws/build/warehouse_ros/CMakeFiles/CMakeTmp/testCCompiler.c
      ccache: error: Failed to create directory /home/runner/work/warehouse_ros/warehouse_ros//root/.ccache/tmp: Read-only file system
      make[1]: *** [CMakeFiles/cmTC_af595.dir/build.make:66: CMakeFiles/cmTC_af595.dir/testCCompiler.c.o] Error 1
      make[1]: Leaving directory '/root/target_ws/build/warehouse_ros/CMakeFiles/CMakeTmp'
      make: *** [Makefile:121: cmTC_af595/fast] Error 2
      
      
  
    
  
    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)
```

**Comment by tylerjw** [comment]
I thought this was a cache ownership issue but it is probably something else.

**Comment by rhaschke** [comment]
I think this issue comes from [changing the `CCACHE_DIR`](https://github.com/ros-planning/warehouse_ros/pull/55/files#diff-e447da8c00f074dde3c24dec1973e22b26eeddf0553735924b5af2aad60f7ca0L23-R23) in #55. Sorry for premature merging. :cry:

**Comment by tylerjw** [comment]
The action takes  3min to run without a ccache.  I'm not sure it is worth it.  

That huge error you saw before was because of the old way I was specifying the home directory.  According to the github docs you shouldn't rely on the absolute path of the home directory and instead you should use the $HOME variable so that is why I changed it.

The error about the compiler I've seen before with ccache when the user doesn't have the right permissions for the ccache folder.  The thing that is weird is if you looked at the cache step of these runs the cache wasn't being found at all.

**Review by rhaschke — COMMENTED** [review]
Hm. While it might be not important to have ccache for this repo, we should figure out how that works in general... Have you seen other repos successfully employing `industrial_ci` with caching?

**Review by rhaschke — APPROVED** [review]

**Comment by tylerjw** [comment]
I have but I think something changed in github actions with regard to environment variables and industrial_ci's template needs to be updated.  The reason I say this is the private repo where we are using this is now failing with the same errors (in the cache step).  I'll try to figure that out and tag you when I have it working again.

**Pull request merged**
