### PR TITLE
Add badges for CI to README

### PR DESCRIPTION
**Pull request by tylerjw**

### CODE REVIEW

**Review by JafarAbdi — APPROVED** [review]

**Comment by rhaschke** [comment]
Why would you have badges for another branch shown? Wouldn't it make sense to restrict badges to the current branch only?

**Comment by JafarAbdi** [comment]
> Why would you have badges for another branch shown? Wouldn't it make sense to restrict badges to the current branch only?

I thought it's ok since this's how we do it in [MoveIt](https://github.com/ros-planning/moveit#continuous-integration), this's why I merged it

**Comment by tylerjw** [comment]
Because the user will often just see the README on the default branch.  I figured it should just be the same on all branches.

My impression was that these badges were more of just something to glance at and we should show the state on all the branches (so someone going to the repo on github can quickly see if any of them are failing).  I can change it so it is per-branch if you think that makes more sense.

**Comment by rhaschke** [comment]
I can follow your reasoning. I wouldn't have done it. However, I don't care too much about this. :wink:

**Pull request merged**
