### PR TITLE
Refactored Warehouse ROS for pluginlib

### PR DESCRIPTION
**Pull request by TheBrewCrew**
This factors out all MongoDB code into a separate package, warehouse_ros_mongo, and creates an abstraction for warehouse clients to use so that warehouse_ros can be built for non LTS versions of Ubuntu and Jade.  Pluginlib is used to load the Mongo code dynamically.

### CODE REVIEW

**Comment by isucan** [comment]
Changes look good, thanks for doing this! The travis build fails here though.

**Comment by mikeferguson** [comment]
@isucan Travis won't work for Jade (since it is trusty+ and travis only supports precise).

**Comment by mikeferguson** [comment]
Also, once this and the other PR are merged, we will want to move https://github.com/TheBrewCrew/warehouse_ros_mongo into the organization as it is the home of the new plugin for mongodb.

**Comment by vrabaud** [comment]
can we move forward on this one ? Robot specific moveit packages cannot be released on Jade because of that. Thx

**Comment by marcoesposito1988** [comment]
I quote that. At least Mongo is made optional and the rest of MoveIt can be used.

**Comment by mikeferguson** [comment]
I'm planning to have time this weekend to make a pass through these and some others and get stuff building/released in Jade

**Comment by vrabaud** [comment]
@mikeferguson , this would be important for a personal project: I can help this weekend on stupid build issues (or release, just grant me rights there if needed and I can commit / trigger builds). Thx !

**Comment by marcoesposito1988** [comment]
ping?

**Comment by vrabaud** [comment]
Travis now supports Trusty so please re-enable. E.g.
https://github.com/ros-perception/vision_opencv/blob/indigo/.travis.yml

**Comment by anderwm** [comment]
Not sure if I am missing something or if this still isn't done yet:  With [brewCrew's code](https://github.com/TheBrewCrew/warehouse_ros.git) I still cannot build moveIt for Jade on Vivid.  I get the "variables used but set to not found".  Am I using it wrong or is this not yet a functional work around?

**Comment by 130s** [comment]
> Travis now supports Trusty so please re-enable. E.g. https://github.com/ros-perception/vision_opencv/blob/indigo/.travis.yml

I'm trying to adjust Travis for Trusty in #26.

**Comment by davetcoleman** [comment]
i just restarted travis for this PR

**Comment by 130s** [comment]
This PR:
-     is conflicted
-    contains some undesired removal (changelog, .travis.yml)
-    and yes, travis isn't triggered properly.

Let's move on to #32 that I re-opened this PR.

**Pull request closed without merging**
