### PR TITLE
Simplifiy on line in Action yaml and add ccache

### PR DESCRIPTION
**Pull request by tylerjw**
@rhaschke I'm sorry I merged that PR too quickly.  Here are the changes you suggested (this time for the ros2 branch).

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
May I ask to add caching here as well, now that you figured out how it works?

**Comment by tylerjw** [comment]
> May I ask to add caching here as well, now that you figured out how it works?

https://github.com/ros-planning/warehouse_ros/pull/58

**Comment by tylerjw** [comment]
Would you like me to combine this with the other change into one PR?

**Comment by rhaschke** [comment]
> Would you like me to combine this with the other change into one PR?

Actually, yes, please. We shouldn't have an excessive amount of tiny maintenance commits.

**Review by rhaschke — APPROVED** [review]
+1 if CI succeeds.

**Review by rhaschke — APPROVED** [review]

**Pull request merged**
